Repository WPBuddy/largo, pull requests merged in 2018-11, with the labels that each got.

#1556 Replace is_home with is_front_page in several places
  docs/developers/hooksfilters.rst
  inc/ajax-functions.php
  inc/enqueue.php
  inc/header-footer.php
  inc/open-graph.php
  inc/post-tags.php
  inc/verify.php
  partials/nav-global.php
  partials/nav-main.php
Labels: type: feature request

#1502 Remove INN/Largo Project Google Analytics tracking from Largo.
  changelog.md
  inc/enqueue.php
Labels: priority: normal

#1557 Add WordPress 5.0 to travis list, remove 4.5 from PHP 5.6 and 4.8 from PHP 7.1
  .travis.yml
Labels: status: needs tests, type: pre-launch todo

#1558 More undefined variables
  changelog.md
  inc/avatars/functions.php
  inc/term-sidebars.php
Labels: priority: normal, type: bug

#1559 Use more-precise conditional for current_user_can in largo byline class
  inc/byline_class.php
Labels: type: bug

#1561 Add warning output if WP_DEBUG || LARGO_DEBUG about the third parameter of largo_byline being required
  changelog.md
  homepages/templates/top-stories.php
  inc/post-tags.php
  inc/widgets/largo-related-posts.php
  partials/archive-category-primary-feature.php
  partials/content-roundup.php
  partials/content-single-classic.php
  partials/content-single.php
  partials/content.php
  partials/sticky-posts.php
  partials/widget-content.php
  series-landing.php
Labels: type: bug

#1562 Add the actions largo_lmp_before_posts and largo_lmp_after_posts to enable wrapping the Load More Posts return with other HTML.
  inc/ajax-functions.php
Labels: type: feature request

#1563 Copy https://github.com/INN/largo/pull/1469 into 0.5-dev
  changelog.md
  inc/widgets/largo-about.php
  partials/footer-widget-3col-default.php
  partials/footer-widget-3col-equal.php
  partials/footer-widget-4col.php
  partials/sidebar-fallback.php
Labels: community contribution, type: bug

#1565 Removes most uses of extract()
  changelog.md
  homepages/homepage-class.php
  inc/editor.php
  inc/enqueue.php
  inc/pagination.php
  inc/users.php
  inc/widgets/largo-author-bio.php
  inc/widgets/largo-disclaimer-widget.php
  inc/widgets/largo-donate.php
  inc/widgets/largo-facebook.php
  inc/widgets/largo-follow.php
  inc/widgets/largo-image-widget.php
  inc/widgets/largo-post-series-links.php
  inc/widgets/largo-prev-next-post-links.php
  inc/widgets/largo-recent-comments.php
  inc/widgets/largo-recent-posts.php
  inc/widgets/largo-related-posts.php
  inc/widgets/largo-series-posts.php
  inc/widgets/largo-staff.php
  inc/widgets/largo-tag-list.php
  inc/widgets/largo-taxonomy-list.php
  inc/widgets/largo-twitter.php
  lib/navis-media-credit/navis-media-credit.php
Labels: priority: high, type: bug

#1566 Actually implement 'title-tag' theme support
  changelog.md
  header.php
  inc/featured-media.php
  inc/open-graph.php
  inc/related-content.php
  partials/archive-category-primary-feature.php
  partials/archive-category-secondary-feature.php
Labels: type: bug, type: tech debt

#1567 Don't add_action( 'wp_head', 'largo_opengraph' ) if Yoast is active.
  changelog.md
  inc/open-graph.php
Labels: type: feature request

#1574 updating largo_byline call in partials
  changelog.md
  homepages/templates/top-stories.php
  partials/content-roundup.php
  partials/content-single-classic.php
  partials/content-single.php
  partials/content.php
  partials/sticky-posts.php
  series-landing.php
Labels: type: bug

#1575 Change enqueues to use filemtime instead of no version number or Largo's version number
  changelog.md
  inc/ajax-functions.php
  inc/avatars/admin.php
  inc/customizer/customizer.php
  inc/enqueue.php
  inc/featured-media.php
  inc/post-metaboxes.php
  inc/term-icons.php
  inc/update.php
  inc/widgets/largo-image-widget.php
  inc/widgets/largo-twitter.php
  inc/wp-taxonomy-landing/functions/cftl-admin.php
  lib/options-framework/options-framework.php
  lib/options-framework/options-medialibrary-uploader.php
Labels: type: improvement

#1578 Prevent "Division by zero" in avatar functions.
  inc/avatars/functions.php
Labels: priority: normal, type: bug
