Repository WPBuddy/largo, pull requests merged in 2019-07, with the labels that each got.

#1736 Check if $instance['title'] is empty rather than $title for Largo Image Widget
  changelog.md
  inc/widgets/largo-image-widget.php
Labels: Estimate: < 2 Hours, priority: normal

#1735 Added `wp_body_open` hook under opening body tag
  changelog.md
  header.php
Labels: Estimate: < 2 Hours, priority: high

#1742 Added `font-display:block` attribute to `fontello` font family
  changelog.md
  css/style.css
  css/style.min.css
  less/inc/icons.less
Labels: Estimate: < 2 Hours, category: styles, priority: low, type: improvement

#1734 Swapped out series post widget image location for image size + alignment options
  changelog.md
  css/style.css
  css/style.min.css
  inc/widgets/largo-series-posts.php
  less/inc/widgets/largo-series-posts.less
Labels: Estimate: < 4 Hours, priority: high, type: feature request

#1743 Make sure the gallery doesn't have a `navis-before` child on open
  lib/navis-slideshows/js/navis-slideshows.js
Labels: Estimate: < 6 Hours, category: images, priority: normal, type: bug

#1747 Fix for images being misaligned in paragraphs
  changelog.md
  css/style.css
  css/style.min.css
  less/inc/gutenberg-shim-16241.less
  less/style.less
Labels: Estimate: < 2 Hours, category: gutenberg, category: styles, priority: low, type: bug, type: feature request

#1733 Output largo specific photo credit metadata on image block
  changelog.md
  functions.php
  inc/gutenberg-block-edits.php
  js/blocks-image-customization.js
  lib/navis-media-credit/navis-media-credit.php
Labels: Estimate: < 4 Hours, category: gutenberg, category: images, priority: high, type: improvement

#1746 Add pullquote specific styles
  changelog.md
  css/editor-style.css
  css/editor-style.min.css
  css/gutenberg.css
  css/gutenberg.min.css
  css/style.css
  css/style.min.css
  homepages/assets/css/single.min.css
  less/inc/blocks-editor.less
  less/inc/blocks.less
  less/inc/posts-and-pages.less
  less/inc/typography.less
Labels: Estimate: < 6 Hours, category: gutenberg, category: styles, priority: normal, type: bug, type: feature request

#1662 Yet Another Sticky Nav PR
  Gruntfile.js
  css/style.css
  css/style.min.css
  js/navigation.js
  js/navigation.min.js
  less/inc/navbar-sticky.less
  options.php
Labels: Estimate: < 4 Hours, status: needs review, type: bug, type: improvement

#1752 Save the Largo Release Checklist in Largo's developer docs
  docs/SUPPORT.rst
  docs/api/index.rst
  docs/developers/child-themes/advanced-development.rst
  docs/developers/child-themes/basic-style-changes.rst
  docs/developers/child-themes/creating.rst
  docs/developers/index.rst
  docs/developers/release-checklist.rst
  docs/developers/upgrade-largo.rst
  docs/index.rst
Labels: status: needs review

#1711 Added `box-sizing: border-box;` to...
  changelog.md
  css/editor-style.css
  css/editor-style.min.css
  css/gutenberg.css
  css/gutenberg.min.css
  css/style.css
  css/style.min.css
  homepages/assets/css/single.min.css
  less/inc/blocks.less
  less/inc/images.less
  less/inc/posts-and-pages.less
  lib/navis-slideshows/css/slides.css
Labels: Estimate: < 2 Hours, category: gutenberg, category: images, category: styles, status: needs research

#1755 Fix Twitter metadata being improperly output to page before global nav
  inc/open-graph.php
Labels: type: bug

#1757 Bump version number from 0.6.4-prerelease to 0.6.4
  css/editor-style.min.css
  css/style.min.css
  docs/api/inc/gutenberg-block-edits.rst
  docs/api/inc/open-graph.rst
  docs/conf.py
  docs/developers/release-checklist.rst
  homepages/assets/css/single.min.css
  lang/es_ES.po
  lang/largo.pot
  style.css
Labels: type: pre-launch todo

#1759 1704 postrelease checklist update
  docs/developers/release-checklist.rst
  readme.md
Labels: Estimate: < 2 Hours, priority: high, status: needs review, type: improvement, type: pre-launch todo
