Repository WPBuddy/largo, pull requests merged in 2019-04, with the labels that each got.

#1666 made largo_get_term_meta_post 'pluggable' so it can be overridden
  inc/term-meta.php
Labels: community contribution, type: feature request

#1668 Added another portion to largo_category_archive_posts conditional
  changelog.md
  inc/featured-content.php
Labels: type: bug

#1655 Mark the Prominence metabox as a backwards-compatibility metabox
  changelog.md
  inc/post-metaboxes.php
Labels: priority: normal, status: needs review, type: bug, type: gutenberg

#1584 Register new thumbnail image size rect_thumb_half, at 400x300, cropped
  changelog.md
  functions.php
Labels: type: feature request, type: improvement

#1613 Use empty() check in conditional in largo_maybe_top_term
  inc/post-tags.php
Labels: priority: normal, status: needs review

#1589 require_once normalization
  changelog.md
  functions.php
  homepages/homepage-class.php
  inc/avatars/admin.php
Labels: priority: normal, type: improvement, type: tech debt

#1672 Register the new image size 96x96 for avatars
  changelog.md
  functions.php
Labels: type: bug

#1673 Prevent header/footer ad widget containers from going beyond the viewport
  changelog.md
  css/editor-style.min.css
  css/style.css
  css/style.min.css
  less/inc/ads.less
Labels: styles, type: bug

#1674 Use wp_no_robots() on non-public blogs, on 404, and on search pages.
  changelog.md
  inc/header-footer.php
Labels: priority: high

#1671 Full-width images regardless of alignment when up to 768px
  changelog.md
  css/editor-style.css
  css/editor-style.min.css
  css/gutenberg.css
  css/gutenberg.min.css
  css/style.css
  css/style.min.css
  less/inc/blocks.less
  less/inc/posts-and-pages.less
  less/inc/responsive-767px-max.less
Labels: community contribution, gutenberg, styles, type: improvement

#1544 Sticky nav menu dropdowns on touchscreen computers
  css/style.css
  css/style.min.css
  inc/enqueue.php
  js/largoCore.min.js
  js/modernizr.custom.js
  js/navigation.js
  js/navigation.min.js
  less/inc/navbar-common.less
Labels: priority: high, type: bug, type: tech debt

#1684 removed extraneous </a> tag from menus
  inc/nav-menus.php
  inc/widgets/largo-related-posts.php
Labels: community contribution, status: needs review

#1687 Block quote styles
  changelog.md
  css/editor-style.css
  css/editor-style.min.css
  css/style.css
  css/style.min.css
  homepages/assets/css/single.min.css
  less/inc/blocks-editor.less
  less/inc/posts-and-pages.less
  less/inc/typography.less
Labels: styles, type: bug

#1689 Add theme support for responsive-embeds
  changelog.md
  functions.php
Labels: gutenberg, priority: normal, type: bug, type: feature request

#1695 Navis Slideshow expand-on-click styles, again.
  changelog.md
  css/gutenberg.css
  css/gutenberg.min.css
  css/style.css
  css/style.min.css
  docs/conf.py
  inc/enqueue.php
  lang/largo.pot
  less/gutenberg.less
  less/inc/header.less
  less/inc/images.less
  lib/navis-slideshows/css/slides.css
  lib/navis-slideshows/js/navis-slideshows.js
  package.json
  style.css
Labels: gutenberg, status: in progress, styles, type: bug
