Repository WPBuddy/largo, pull requests merged in 2019-06, with the labels that each got.

#1715 Fix ReferenceError in navigation.js
  changelog.md
  js/navigation.js
  js/navigation.min.js
Labels: Estimate: < 2 Hours, priority: normal, type: bug

#1724 Fix undefined $description in largo_opengraph() and apply WP Code Standards
  changelog.md
  inc/open-graph.php
  tests/inc/test-open-graph.php
Labels: type: bug

#1726 Remove HTML from labels of Co-Authors Plus additional profile fields.
  changelog.md
  inc/users.php
Labels: category: plugin compat, type: bug, type: improvement

#1728 Fix for `Undefined variable $post in homepage/templates/top-stories.php`
  changelog.md
  homepages/templates/top-stories.php
Labels: Estimate: < 2 Hours, priority: low, type: bug

#1729 Plugin compatibility testing docs
  docs/developers/index.rst
  docs/developers/plugin-compat.rst
  docs/developers/technicalnotes.rst
Labels: category: plugin compat
