Repository WPBuddy/largo, pull requests merged in 2019-03, with the labels that each got.

#1633 Update footer INN logos
  changelog.md
  img/README.md
  img/inn_dark.png
  img/inn_dark.svg
  img/inn_light.png
  img/inn_light.svg
  img/inn_logo_blue_final.png
  img/inn_logo_gray.png
  img/inn_logo_reversetype.png
  inc/header-footer.php
  tests/inc/test-header-footer.php
Labels: priority: normal

#1635 Various Floating Social Buttons improvements
  changelog.md
  css/editor-style.css
  css/editor-style.min.css
  css/style.css
  css/style.min.css
  inc/post-social.php
  less/inc/single.less
Labels: priority: normal, type: bug, type: improvement

#1645 Fix bug in largo_module_shortcode where shortcode content was not being displayed
  inc/editor.php
Labels: priority: normal, type: bug

#1648 Add term class to largo_top_term() output, prevent largo_category_and_tags() from using wrong post in fallback scenario.
  changelog.md
  homepages/zones/zones.php
  inc/related-content.php
Labels: type: bug, type: feature request, type: improvement

#1657 Add a second parameter to the largo_byline filter, containing an array of the arguments used in largo_byline()
  changelog.md
  inc/post-tags.php
Labels: type: feature request, type: improvement
