Repository WPBuddy/largo, pull requests merged in 2021-03, with the labels that each got.

#1876 Add Mx. as known honorifics
  inc/post-tags.php
Labels: community contribution, hacktoberfest, priority: low

#1778 1777 Project Largo Help dashboard widget updates
  changelog.md
  inc/dashboard.php
Labels: status: needs review, type: bug, type: feature request

#1887 1885 - Post-social.php syntax issue
  changelog.md
  inc/post-social.php
Labels: category: clean up, priority: high, status: needs review, type: bug

#1886 1884 - Post-social.php syntax error
  changelog.md
  inc/post-social.php
Labels: category: clean up, priority: high, status: needs review, type: bug

#1888 #1874 theme images 'upload' buttons not responding
  changelog.md
  lib/options-framework/js/of-medialibrary-uploader.js
Labels: category: clean up, priority: high, status: needs review, type: bug, type: tech debt

#1895 Updated README.md
  readme.md
Labels: status: needs review

#1898 1526 - Replace file get contents
  changelog.md
  inc/avatars/admin.php
Labels: category: clean up, community contribution, hacktoberfest, type: tech debt
