Repository WPBuddy/largo, pull requests merged in 2021-04, with the labels that each got.

#1812 Feature/1791 add discernible text label to author twitter links
  inc/byline_class.php
  inc/post-social.php
  partials/author-bio-social-links.php
Labels: category: accessibility, community contribution, hacktoberfest, priority: normal

#1903 #1776 - Fix largo_top_term title attribute output so that correct taxonomy label is used
  changelog.md
  inc/related-content.php
Labels: category: accessibility

#1840 Widget titles (and other improvements) for Twitter and Facebook widgets
  changelog.md
  inc/widgets.php
  inc/widgets/largo-facebook.php
  inc/widgets/largo-twitter.php
Labels: community contribution

#1811 feat: #1785 Remove maximum scale
  header.php
Labels: category: accessibility

#1905 #1904 landing page post order select field throwing error when adding new lp
  changelog.md
  inc/wp-taxonomy-landing/functions/cftl-admin.php
Labels: type: bug

#1902 1901 - Add in order=ASC on the "ASC" case for series landing page posts
  changelog.md
  series-landing.php
Labels: status: needs review, type: bug

#1900 #1870 - Fix landing page options not showing their true saved value
  changelog.md
  inc/wp-taxonomy-landing/functions/cftl-admin.php
Labels: priority: normal, status: needs review, type: bug

#1899 #1540 update grunt dependencies
  Gruntfile.js
  changelog.md
  css/editor-style.css
  css/editor-style.min.css
  css/featured-media.min.css
  css/gutenberg.css
  css/gutenberg.min.css
  css/style.css
  css/style.min.css
  docs/api/inc/header-footer.rst
  docs/api/inc/widgets/largo-recent-posts.rst
  docs/api/index.rst
  docs/api/options.rst
  homepages/assets/css/legacy-three-column.css
  homepages/assets/css/single.css
  homepages/assets/css/single.min.css
  homepages/assets/css/top-stories.css
  homepages/assets/css/top-stories.min.css
  js/custom-less-variables.min.js
  js/custom-sidebar.min.js
  js/custom-term-icons.min.js
  js/featured-media.min.js
  js/floating-social-buttons.min.js
  js/image-widget.min.js
  js/largoCore.min.js
  js/load-more-posts.min.js
  js/navigation.min.js
  js/top-terms.min.js
  js/update-page.min.js
  js/widgets-php.min.js
  package-lock.json
  package.json
Labels: Estimate: < 2 Hours, category: clean up, priority: normal, status: needs review, type: improvement

#1877 Fix Largo_Related::popularity_sort sort
  changelog.md
  inc/related-content.php
Labels: community contribution, hacktoberfest

#1856 Document existence of other image sizes, thumbnail size change
  docs/developers/imagesizes.rst
Labels: community contribution, status: needs review, type: improvement
